# Generated by Django 5.2.13 on 2026-05-01 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymovement',
            name='movement_type',
            field=models.CharField(choices=[('opening', 'Opening'), ('invoice_sale', 'Invoice sale'), ('purchase_receive', 'Purchase receive'), ('invoice_reversal', 'Invoice reversal'), ('adjustment', 'Adjustment')], max_length=40),
        ),
    ]
